FROM almalinux:9
RUN dnf install nginx -y
# there is no functionality for EXPOSE, it is just for information
LABEL project="expense" \
      environment="dev" \
      components="frontend" \
      author="siva" 